2019-11-07 11:43:09,940 [INFO ]  Starting Rasa server on http://localhost:5005
2019-11-07 11:43:23,908 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-11-07 11:48:04,136 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/model/parse'
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 446, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method GET not allowed for URL /model/parse
2019-11-07 11:50:15,304 [INFO ]  Starting Rasa server on http://localhost:5005
2019-11-07 11:50:29,179 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-11-07 11:56:57,510 [INFO ]  Starting Rasa server on http://localhost:5005
2019-11-07 11:57:09,977 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
